### ISSUE TITLE
All filesystem changes cause my server to crash

### ISSUE THREAD

**Issue by brandon-arnold** [cytb/simple-autoreload-server#1]
Hi all,

My auto-reload isn't working, because as soon as any file is created, saved, etc., the server crashes with the following output:

```powershell
C:\Projects\myApp>autoreload-server C:\Projects\myApp 8080
[autoreload #15652 localhost:8080] server started on :8080 at C:\Projects\myApp

path.js:204
        throw new TypeError('Arguments to path.join must be strings');
        ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at FSWatcher.<anonymous> (C:\Users\212438903\AppData\Roaming\npm\node_module
s\simple-autoreload-server\lib\watch.js:12:1019)
    at FSWatcher.emit (events.js:98:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1050:12)
```

This would happen if I add a space to `C:\Projects\myApp\index.html`, for example, and save it.

Any ideas what I could do to fix it?

Thanks,
Brandon

**Comment by cytb** [comment]
Thank you so much for reporting the issue. but sorry for replying so late.

IThat error wont be occued when  I tried on node v0.12.0, WinXP-Pro

It may be caused by 'change' event listener of fs-watcher.
and I'll fix listener-function to check directory/file invalid or not.
