### ISSUE TITLE
Disable browser console output

### ISSUE THREAD

**Issue by davestewart** [cytb/simple-autoreload-server#2]
Can the browser console logging be disabled?

On every reload I get a ton of blue messages, which I really don't need, and get in the way of the console output I do want to see.

**Comment by davestewart** [comment]
In case anyone else would like to do the same, I've disabled it in the meantime by hacking the installed module code:
![autoreload-server-no-console-output](https://cloud.githubusercontent.com/assets/132681/12373839/7c28404c-bc80-11e5-9dc4-643326de7c06.png)

**Comment by cytb** [comment]
I modified codes, and now browser logging disabled by default.
You can re-enable logging by command-llne option (--client-log).

Thank you for using and reporting!

**Comment by davestewart** [comment]
That's great, thanks!

Actually I sent you an email yesterday, to the aol address listed on the NPM page, but it bounced. Anyway, FYI, it said:

> I just wanted to say THANK YOU SO MUCH for this tool!
>
> I've been looking for something as simple and effective as this for ages.
> I had a simple package.json and gulpfile that I take from project to project, but for quick hacking or learning this is absolutely unbeatable! (maybe the name could be easier to remember; I might alias it)
>
> I'm amazed it took me so long to track down; it deserves more exposure.
> 
> Cheers again,
> 
> Dave Stewart

**Comment by cytb** [comment]
Excuse me, I confirmed my AOL account had been deavtivated.
I used AOL as email forwarding service and currently activated.

> FYI, it said:

It encourages me!  Thank you!
