### ISSUE TITLE
Loading failed for index.html which is UTF-8 with BOM

### ISSUE THREAD

**Issue by jomo0825** [cytb/simple-autoreload-server#4]
If the index.html is a UTF-8 with BOM, the file will be treated as a plain text in browser.

**Comment by cytb** [comment]
Thank you for your reporting!

I confirmed the bug on my environment. the server gives no "content-type" header.

Server Response: 
>HTTP/1.1 200 OK
>Content-Length: 16655
>Date: Sun, 10 Apr 2016 07:19:33 GMT
>Connection: keep-alive

Now I fixed it. 
>HTTP/1.1 200 OK
>Content-Length: 16655
>Content-Type: text/html
>Date: Sun, 10 Apr 2016 09:47:46 GMT
>Connection: keep-alive

Please update and try again!

**Comment by jomo0825** [comment]
It works perfect now! Thank you for all your great efforts~~ I'll recommend all my friends to use this module.

**Comment by cytb** [comment]
I'm glad to hear that!
Thank you for your support. It encourages me.
