### ISSUE TITLE
Autoreload does not work when page is opened on another device.

### ISSUE THREAD

**Issue by Franky47** [cytb/simple-autoreload-server#6]
Auto-reloading works correctly when using localhost as the URL on the same machine as where autoreload-server is running, but if I browse to mydevmachine.local:8080 on another machine that is on the same network, the page shows up correctly (dev server works) but changes are not auto-reloaded on the distant machine. Manually reloading shows the changes.

**Comment by Franky47** [comment]
It makes sense, as the autoreload code is not injected into the HTML page on the distant machine (but is correctly injected and connected to the websocket on the dev machine).

**Comment by Franky47** [comment]
Found my issue: when disabling `listDirectory` and navigating to `http://{host}:{port}/`, livereload does not work (no injection of the livereload js code), but using `http://{host}:{port}/index.html` works.

**Comment by cytb** [comment]
Thank you  for reporting the issue.
