### ISSUE TITLE
Npm vulnerabilities

### ISSUE THREAD

**Issue by aattrell** [cytb/simple-autoreload-server#7]
Hi all,

I've noticed some npm security vulnerabilities when using your package (with node --version 10.4.0). All of these would be fixed by updating to connect 3.6.6 - is that something you will be doing in the future?

High: Denial-of-Service Memory Exhaustion
Package: qs
Patched in: >= 1.x
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > qs
More info: https://nodesecurity.io/advisories/29

High: Denial-of-Service Extended Event Loop Blocking
Package: qs
Patched in: >= 1.x
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > qs
More info: https://nodesecurity.io/advisories/28

High: Regular Expression Denial of Service
Package: fresh
Patched in: >= 0.5.2
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > fresh
More info: https://nodesecurity.io/advisories/526

High: Regular Expression Denial of Service
Package: fresh
Patched in: >= 0.5.2
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > send > fresh
More info: https://nodesecurity.io/advisories/526

High: Regular Expression Denial of Service
Package: negotiator
Patched in: >= 0.6.1
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > negotiator
More info: https://nodesecurity.io/advisories/106

Moderate: Timing Attack
Package: cookie-signature
Patched in: >=1.0.6
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > cookie-signature
More info: https://nodesecurity.io/advisories/134

Low: Directory Traversal
Package: send
Patched in: >= 0.8.4
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > send
More info: https://nodesecurity.io/advisories/32

Low: Root Path Disclosure
Package: send
Patched in: >=0.11.1
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > send
More info: https://nodesecurity.io/advisories/56

Moderate: Regular Expression Denial of Service
Package: mime
Patched in: >= 1.4.1 < 2.0.0 || >= 2.0.3
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > send > mime
More info: https://nodesecurity.io/advisories/535

Low: Regular Expression Denial of Service
Package: debug
Patched in: >= 2.6.9 < 3.0.0 || >= 3.1.0
Dependency of: simple-autoreload-server [dev]
Path: simple-autoreload-server > connect > debug
More info: https://nodesecurity.io/advisories/534

**Comment by cytb** [comment]
I'm so sorry for late reply...
Now I updated 'connect' package, and fixed related codes.

Thank you for informing me! I was helped.
